services:
  projecteuler-py:
    image: projecteuler-py:latest
    build:
      context: .
      target: testing
    environment:
      _DEBUG: ${_DEBUG}
    volumes:
      - ./coverage:/app/coverage
    profiles: ["testing"]

  projecteuler-py-dev:
    image: projecteuler-py:dev
    build:
      context: .
      target: development
    environment:
      _DEBUG: ${_DEBUG}
    volumes:
      - ./:/app
    profiles: ["development"]
