name: Python

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

env:
  LOG_LEVEL: WARN

jobs:

  build:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os: [
          "windows-latest",
          "ubuntu-latest",
          "macOS-latest"
        ]
        python: ['3.9', '3.10']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python }}

    - name: Install
      run: |
        pip3 install -r requirements.txt

    - name: Lint
      run: |
        pylint --verbose --recursive yes src/

    - name: Test
      run: |
        coverage run -m pytest --verbose src/

    - name: Coverage
      run: |
        coverage report

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
